- name: Hosts file is copied
  copy:
    src: hosts
    dest: /etc/hosts
  tags: [mesos]

- name: Repos are present
  yum:
    name: "{{ item }}"
    state: present
  with_items: repos
  tags: [mesos]

- name: Packages are installed
  yum:
    pkg: "{{ item }}"
    state: present
  with_items: packages
  tags: [mesos]

- include: master.yml
  when: mesos_master is defined

- include: node.yml
  when: not mesos_master is defined

- name: Containerizers are copied
  copy:
    src: containerizers
    dest: /etc/mesos-slave/containerizers
  tags: [mesos]

- name: Mesos slave is started
  service:
    name: mesos-slave
    state: started
  tags: [mesos]
